### ISSUE TITLE
Swiping up and down

### ISSUE THREAD

**Issue by vanshg** [wenchaojiang/AndroidSwipeableCardStack#1]
In addition to the swiping left and right to "like" or "dislike" something, is it possible to also add the ability to swipe up and down for other actions?

**Comment by wenchaojiang** [comment]
As I have documented in readme.md, the component can recognise directions to four corners, not UP, DOWN.  But, one workaround is to treat up two corners as UP, and two bottom corners as DOWN.

**Comment by vanshg** [comment]
But if I do it that way, then i can't do left and right as well. I want to
have all 4 directoins. Is there a way to redefine the sections?
ᐧ

On Thu, Jul 9, 2015 at 12:52 AM, wenchao jiang notifications@github.com
wrote:

> As I have documented in readme.md, the component can recognise directions
> to four corners, not UP, DOWN. But, one workaround is to treat up two
> corners as UP, and two bottom corners as DOWN.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wenchaojiang/AndroidSwipeableCardStack/issues/1#issuecomment-119861867
> .

## 

Vansh Gandhi

**Comment by wenchaojiang** [comment]
I do not know what you want to achieve. Do you want to change the direction of card (leaving) animation or just want to reinterpret the direction of user swipe event.

The formal requires a more hacking into the project code.
If it is the latter, there is a easy workaround:

You can checkout of documentation of the swipe event callback, which report x, y distance  (away from center), and the direction in original framing.
   public boolean swipeContinue(int direction, float distanceX, float distanceY) {
        return true;
    }
You got all the information you need,  Just translate the corner directions to UP, DOWN, LEFT ,RIGHT.
