### ISSUE TITLE
I want use this in api lever 14 but there are some error 

### ISSUE THREAD

**Issue by yangyu5646** [wenchaojiang/AndroidSwipeableCardStack#10]
I want use this in api level 14.There are some error in Androidstudio. 
  In class CardAnimator 54 line .  
  baseLayout = new RelativeLayout.LayoutParams(baseLayout); 
  there is no this method    RelativeLayout.LayoutParams(RelativeLayout.LayoutParams source),in api level 14. Can you give some advise to me ?

**Comment by wenchaojiang** [comment]
Hmmm... could you post your build.gradle?

It should not compile, because the constructor is only introduced in level 19. But it does pass compilation on my machine, very weird.

I will consider rewrite this line anyway.

**Comment by yangyu5646** [comment]
I modify the build.gradle to make it  compile.  
 If there is progress Please inform me. 
 Thank you very much .

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.1'

```
defaultConfig {
    applicationId "wxj.swipeablecardstack"
    minSdkVersion 14
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    //compile(name:'android-card-stack-0.1.0', ext:'aar')
    //http://stackoverflow.com/questions/21170395/how-to-include-a-library-module-dependency-in-an-android-studio-project
    compile project(":CardStack")
    compile 'com.android.support:appcompat-v7:20.0.+'
}

**Comment by broakenmedia** [comment]
How does this support API 14 when it uses api's from level 19? I.e. RelativeLayout.LayoutParams copy constructor?

**Comment by silviahisham** [comment]
same happens to me

**Comment by spartacus777** [comment]
+1 for
"How does this support API 14 when it uses api's from level 19? I.e. RelativeLayout.LayoutParams copy constructor?"

**Comment by spartacus777** [comment]
Fix in project description min API level 19, cuz this won't work for previous API, I checked out, and even tryied quick fixes, but failed.

**Comment by wenchaojiang** [comment]
I am a bit confused at the moment. 
Here is my gradle with 14 minSdk, it compiles and runs fine. I do agree with you, with that constructor it should not work, but why it works here for me. Enlighten me plz!

-------- gredle

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 21
    buildToolsVersion '23.0.2'

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.2'
}
```

**Comment by wenchaojiang** [comment]
Ha, I found it does not work, my device simulator is above api 14. 

So the current plan for next patch is to hand write a copy constructor for the RelativeLayout, should not be difficult.

**Comment by wenchaojiang** [comment]
I'd appreciate if anyone can test on this patch
d5c4206a328518c618c58c9622dfcf725d2d9975

**Comment by razor-rs** [comment]
Hi,  have same problme on Android 4.2.2 when I try to run app crash, and with you last patch that problem has been resolved but now when I try to swipe on Android 4.2.2 I get this erro:

java.lang.NoSuchMethodError: android.widget.RelativeLayout$LayoutParams.<init>
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at com.wenchao.animation.RelativeLayoutParamsEvaluator.evaluate(RelativeLayoutParamsEvaluator.java:13)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at com.wenchao.animation.RelativeLayoutParamsEvaluator.evaluate(RelativeLayoutParamsEvaluator.java:7)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.animation.KeyframeSet.getValue(KeyframeSet.java:170)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:660)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1161)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1102)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1131)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:509)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.animation.ValueAnimator.start(ValueAnimator.java:913)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.animation.ValueAnimator.start(ValueAnimator.java:923)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at com.wenchao.cardstack.CardAnimator.reverse(CardAnimator.java:219)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at com.wenchao.cardstack.CardStack$2.onDragEnd(CardStack.java:179)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at com.wenchao.cardstack.DragGestureDetector.onTouchEvent(DragGestureDetector.java:40)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at com.wenchao.cardstack.CardStack$3.onTouch(CardStack.java:196)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.View.dispatchTouchEvent(View.java:7672)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2395)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2305)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1575)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.app.Activity.dispatchTouchEvent(Activity.java:2470)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2253)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.View.dispatchPointerEvent(View.java:7875)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3978)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3862)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5105)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5084)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5182)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.os.MessageQueue.nativePollOnce(Native Method)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.os.MessageQueue.next(MessageQueue.java:125)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:138)
12-19 04:38:50.188 20094-20094/? E/AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.j

**Comment by razor-rs** [comment]
I have fixed this when change this class:

public class RelativeLayoutParamsEvaluator implements TypeEvaluator<LayoutParams> {

```
@Override
public LayoutParams evaluate(float fraction, LayoutParams start,
                             LayoutParams end) {

    LayoutParams result = start;
    result.leftMargin += ((end.leftMargin-start.leftMargin)*fraction);
    result.rightMargin += ((end.rightMargin-start.rightMargin)*fraction);
    result.topMargin += ((end.topMargin-start.topMargin)*fraction);
    result.bottomMargin += ((end.bottomMargin-start.bottomMargin)*fraction);
    return result;
}
```

}

Please can you check if this is valid solution, right now everything working fine for me.

**Comment by wenchaojiang** [comment]
Hi, thanks razor-rs
I updated this patch
31f3ba116ad2019eab072065822b6fda9b09c8e8

I just used a clone method instead of putting a reference.
