### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by clem44** [wenchaojiang/AndroidSwipeableCardStack#11]
How to change the background color of the generated cards?I would like to set one color. If you could guide me to where the card background color is set or created. That would be appreciated. Cheers.

**Comment by vrjgamer** [comment]
There is no way that u can avoid it, its strong coded in the library. Its there in the Class card Animator. 

To change the color, just change this snippet here:

```
    private void setup(){
    mLayoutsMap = new HashMap<View,RelativeLayout.LayoutParams>();
               for(View v : mCardCollection){
               //setup basic layout
               RelativeLayout.LayoutParams params = (RelativeLayout.LayoutParams) v.getLayoutParams();
               params.addRule(RelativeLayout.ALIGN_PARENT_TOP);
               params.width = LayoutParams.MATCH_PARENT;
               params.height = LayoutParams.MATCH_PARENT;
                        // just change this to set the color 
                Random rnd = new Random();
               int color = Color.argb(255, rnd.nextInt(256), rnd.nextInt(256), rnd.nextInt(256));
               v.setBackgroundColor(color);
                v.setLayoutParams(params);
               }
```

**Comment by clem44** [comment]
Hi, yea thanks for the reply. I did find it shorty after messaging you. I just ignorantly assumed it would be located in the CardStack class.

**Comment by wenchaojiang** [comment]
As a workaround, Howabout setting a your customized layout as match_parent
background. And set its bg color,so it can cover the lib bg color?
