### ISSUE TITLE
Gradle dependency

### ISSUE THREAD

**Issue by silviahisham** [wenchaojiang/AndroidSwipeableCardStack#13]
Please provide a gradle dependency link

**Comment by wenchaojiang** [comment]
repositories {
        // ...
        maven { url "https://jitpack.io" }
 }

dependencies {
        compile 'com.github.wenchaojiang:AndroidSwipeableCardStack:0.1.1'
}

Does this work?

**Comment by silviahisham** [comment]
It works well, thanks!
