### ISSUE TITLE
Please remove the ix_launcher.png

### ISSUE THREAD

**Issue by ashokslsk** [wenchaojiang/AndroidSwipeableCardStack#18]
Hi Great work, 

Can you please remove the ic_launcher.png file in the library and post it maven as an update. 
And how can trigger the swipe events on button clicks say 2 buttons left and right if i press left button card should swipe off to left edge of the screen and right button right edge of the screen.

**Comment by wenchaojiang** [comment]
Programmatically call "public void discardTop(final int direction)" method in CardStack.java

**Comment by ashokslsk** [comment]
Oh ok i will try this thanks for solution :+1:  but please do remove the icon and push the build other libraries which uses icons are giving lots of conflict ... hope you will do it :) 

Closing the issue...

cheers :+1:
