### ISSUE TITLE
Overlays

### ISSUE THREAD

**Issue by vanshg** [wenchaojiang/AndroidSwipeableCardStack#2]
Is it possible to get the "like" and "dislike" overlays as you swipe left and right, so that the user knows what action they are taking when swiping?

**Comment by wenchaojiang** [comment]
Yes, you can , just put an overlay on top and listen to swipe event. It is not part of component functionality though.

**Comment by bia-nca** [comment]
is it possible to disable the background color?

**Comment by vanshg** [comment]
How would you go about putting an overlay on top?
