### ISSUE TITLE
WebView in content leaves patch behind

### ISSUE THREAD

**Issue by neeradkumar** [wenchaojiang/AndroidSwipeableCardStack#20]
Very simple to replicate. When there is a webview in content, it leaves a trace behind. Specifically, webview won't rotate

**Comment by neeradkumar** [comment]
Did anyone check this?

**Comment by wenchaojiang** [comment]
I can not reproduce it, seems to be ok
<img width="1280" alt="screen shot 2015-12-17 at 09 38 09" src="https://cloud.githubusercontent.com/assets/784100/11866285/f602728a-a4a1-11e5-99b8-4c891d50ae4e.png">

**Comment by christian160984** [comment]
@wenchaojiang Can you put the code to load a webView?

**Comment by SUBINPTPM** [comment]
https://github.com/wenchaojiang/AndroidSwipeableCardStack/issues/96
