### ISSUE TITLE
Right Left Listener

### ISSUE THREAD

**Issue by ahmadmiraj** [wenchaojiang/AndroidSwipeableCardStack#21]
Can you please help me...How can i know card is swiped right or swiped left ??
how can i implement that listener ??

regards

**Comment by wenchaojiang** [comment]
Suggestion is to treat directions 1,2 as left, 3,4 as right

**Comment by ahmadmiraj** [comment]
can you please mention its code !

**Comment by wenchaojiang** [comment]
Plz look at readme.md, there is a section about it
