### ISSUE TITLE
Is there any way to make the background of the cards to same color?

### ISSUE THREAD

**Issue by varunrramani** [wenchaojiang/AndroidSwipeableCardStack#25]
The background of the cards come in random colours. is it possible to make the colour transparent or of the same colour?

**Comment by SalmanTariq** [comment]
You can clone the library, import it as  a module then change CardAnimator class's line 49. 
Or you can set the background colour of your card layout to a colour you want.

**Comment by juanpabloprado** [comment]
Hi, in my fork there is no background for the cards nor the one behind the cards, is up to the user via a custom attribute or you can use a CardView as the card content and change it from there.

A kind of changelog is on the pull request #27 

Currently you can use it from my bintray repository:

``` java
repositories {
    jcenter()
    maven { url "http://dl.bintray.com/juanpablo/maven" }
}
dependencies {
  compile 'com.wenchao:cardstack:1.1.0'
}
```

**Comment by kedartendolkar** [comment]
Please remove the random background color. It doesn't look good.

**Comment by wenchaojiang** [comment]
done

**Comment by shizznet** [comment]
Hi Regarding same color, the cards are not distinguishable, how can i shade the cards like first card white then second card little greyish then third more greyish. but when I swipe a card then next card displayed should be white not grey.
