### ISSUE TITLE
Custom Layout / Background Color

### ISSUE THREAD

**Issue by bia-nca** [wenchaojiang/AndroidSwipeableCardStack#3]
is it possible to disable the background color?

**Comment by wenchaojiang** [comment]
The code is here:
AndroidSwipeableCardStack/CardStack/src/main/java/com/wenchao/cardstack/CardAnimator.java
Line 47:

Just disable that line ;)

**Comment by bia-nca** [comment]
ok, i thought there might be a better way. but thx :)

**Comment by wenchaojiang** [comment]
I know I know :) not ideal.  you can submit a pull request if you wish
