### ISSUE TITLE
Endless Swiping

### ISSUE THREAD

**Issue by appschris** [wenchaojiang/AndroidSwipeableCardStack#37]
Is it possible to create an endless swipe ?

When last card appears next card will be first card ?

**Comment by appschris** [comment]
Already solved... add card-1 after discarded called

**Comment by Belial09** [comment]
@appsoluts could you give me a little example please. Im trying to get this work. thank you!

**Comment by Belial09** [comment]
at the moment i archieved "endless swipe" like this, Is this the supposed way to do it or should i change it.

``` java

//cardCounter initial value == 0

@Override
public void discarded(int mIndex, int direction) {
    mCardStack.getAdapter().add(cardItems.get(cardCounter));
    if((mIndex)%cardItems.size()==0){
        cardCounter=0;
    }
    else {
        cardCounter++;
    }
}
```

**Comment by wenchaojiang** [comment]
Yes, continuously add discarded card to the end of the adapter can be the solution. 
However, your adapter will continuously grow if user keep swiping. Consider a complete reset at some point, like mCardStack.setAdapter(reconstructedAdapter).

And why you do not need to keep check with cardCounter? It seems mIndex serve the purpose

**Comment by appschris** [comment]
you could override the get method with modulo and let the index grow ! 

Simple solution so far:

`@Override
            public void discarded(int mIndex, int direction) {
                actCard = mIndex;
                try{
                    Story s = mCardAdapter.getItem(mIndex-1);
                    mCardAdapter.add(s);
                }catch (Exception e){

```
            }
        }`
```
