### ISSUE TITLE
Smooth swipe movement

### ISSUE THREAD

**Issue by ihariza** [wenchaojiang/AndroidSwipeableCardStack#38]
There any way to make the swipe movement smoother?
Thanks!

**Comment by wenchaojiang** [comment]
plz define smoother

**Comment by ihariza** [comment]
when you drag the card movement is not smooth like tinder, maybe because x_diff and y_diff in drag method of CardAnimator class is 30 and 60, and in the next step 45 and 87, for example.

**Comment by wenchaojiang** [comment]
I am grouping the issue to here https://github.com/wenchaojiang/AndroidSwipeableCardStack/issues/35
