### ISSUE TITLE
How to add click events to items inside the card?

### ISSUE THREAD

**Issue by silviahisham** [wenchaojiang/AndroidSwipeableCardStack#39]
I tried adding click listeners to certain items inside the card itself, bu it conflicts with the dragging event of the whole card. how can I do it without conflicting with the swiping events ?

**Comment by cprakashagr** [comment]
Try, yourItem.setEnabled(true); and check if click listener is working or not.

**Comment by wenchaojiang** [comment]
https://github.com/wenchaojiang/AndroidSwipeableCardStack/issues/56
