### ISSUE TITLE
Conflict Touch with Viewpager

### ISSUE THREAD

**Issue by bhavikgandhi007** [wenchaojiang/AndroidSwipeableCardStack#40]
I have s ViewPager in CardView, How to touch to move the card. It is conflicted touch event between Viewpager swipe and Cardview swipe left and right

**Comment by wenchaojiang** [comment]
Hmm, you may need to be clear why do you use the card stack. It is for representation, not complicated interaction. That is to say, Why not launch a detailed view for your interactions?

**Comment by wenchaojiang** [comment]
https://github.com/wenchaojiang/AndroidSwipeableCardStack/issues/56
