### ISSUE TITLE
Invisibility for background cards

### ISSUE THREAD

**Issue by cprakashagr** [wenchaojiang/AndroidSwipeableCardStack#42]
Hi,

Is it possible from the existing API to hide the background cards?

Sometime in my app, my top card has a transparent color. The background card cards' child views overlap with my top card child views. Is it possible to hide the background cards and let the top card be only visible at a time?

**Comment by wenchaojiang** [comment]
You can set visible card number with cardstack method

**Comment by cprakashagr** [comment]
Thanks a lot.. :)
