### ISSUE TITLE
Control visible cards transparency

### ISSUE THREAD

**Issue by messer00** [wenchaojiang/AndroidSwipeableCardStack#46]
I have 3 cards visible at a time. I'd like the top one to have 1.0f alpha, one below it 0.5f alpha and the third in the stack 0.3f alpha. Where in the code is the best place to add this functionality in? Unfortunately animations do not persist this effect without setFillAfter.

**Comment by wenchaojiang** [comment]
Look at CardStack.java, you will have to expose viewCollection to your client code. The viewCollection is the collection of the card container. you can set alpha value as you wish
