### ISSUE TITLE
discarded(int index, int direction) receives index of top card and not from the card that has been swiped

### ISSUE THREAD

**Issue by gerardo-navarro** [wenchaojiang/AndroidSwipeableCardStack#47]
Hi Guys,

i wanted to ask why the `CardEventListener` method `discarded(int index, int direction)` receives the index of the top card and not the index of the card that has been discarded. Is there a reason for this?

See https://github.com/wenchaojiang/AndroidSwipeableCardStack/blob/54b3df6143917690501bc491b37ad31518115277/CardStack/src/main/java/com/wenchao/cardstack/CardStack.java#L55

Cheers, Gerardo

**Comment by wenchaojiang** [comment]
fixed in the latest commit 
https://github.com/wenchaojiang/AndroidSwipeableCardStack/commit/26f44c8592e722e73a3c5c6c0a66575d58e4d94a
