### ISSUE TITLE
Undo a Swiped card

### ISSUE THREAD

**Issue by rohannexialabs** [wenchaojiang/AndroidSwipeableCardStack#5]
First of all, thanks for the awesome library. It is working wonderfully, however, I didn't find any way to undo a recently dismissed card. I want the last dismissed card to be displayed back on a click of a button, if user dismissed it accidentally.

How should I do it?

**Comment by wenchaojiang** [comment]
Sorry, the undo animation is not implemented. If you do not require animation, you can reset elements in your adapter (reinsert discarded content ) and reload it.

**Comment by rohannexialabs** [comment]
Thanks for the quick reply, no animation isn't a big issue. Although, it would be cool to have it. I thought there might be a quick way in the API for this issue, anyhow, thanks again for response and a great API.

**Comment by silviahisham** [comment]
+1 would be very cool to have this feature implemented in the future
