### ISSUE TITLE
swipeStart is not implemented in CardStack

### ISSUE THREAD

**Issue by gerardo-navarro** [wenchaojiang/AndroidSwipeableCardStack#50]
The event listener method [`swipeStart`](https://github.com/wenchaojiang/AndroidSwipeableCardStack/blob/master/CardStack/src/main/java/com/wenchao/cardstack/CardStack.java#L44) is not called in [`CardStack`](https://github.com/wenchaojiang/AndroidSwipeableCardStack/blob/master/CardStack)

**Comment by wenchaojiang** [comment]
09d6c4fd63ec8a45d158a2d279b0ba4c2c7a4fe8
