### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by omkardusane** [wenchaojiang/AndroidSwipeableCardStack#52]
How to disable Debug logs in this one ?

**Comment by einverne** [comment]
I find that all logs were written in the lib. You can remove all log functions by yourself. I think there no way to disable logs in this lib.

**Comment by wenchaojiang** [comment]
willfix

**Comment by omkardusane** [comment]
Awesome, Some method should be given..

**Comment by wenchaojiang** [comment]
Through some research, I think the best approach is to use proguard in your project to strip out the log code when building you ur project. 
Please see the DemoApp configuration for details: 
https://github.com/wenchaojiang/AndroidSwipeableCardStack/blob/master/DemoApp/proguard-rules.pro

**Comment by omkardusane** [comment]
Thanks Wenchao
