### ISSUE TITLE
Error:(16, 0) SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable. <a href="openFile:C:\Users\Administrator\Desktop\AndroidSwipeableCardStack-master\CardStack\build.gradle">Open File</a>

### ISSUE THREAD

**Issue by lozn00** [wenchaojiang/AndroidSwipeableCardStack#53]
奇怪的是我自己的项目啥错误都没有搞不懂了。

**Comment by wenchaojiang** [comment]
As no similar issue is reported, it may not be a issue of this lib. I can not help debug a general issue sorry

**Comment by lozn00** [comment]
ok了。 突然就好了 。。我也感觉很那雨梦。。好像各种clear然后重启 各种折腾后终于好了。

**Comment by lozn00** [comment]
对了，有一个bug,设置卡片的行数间距,当行数 刚开始滑动  会发现间距还是原来设置的   出现 了1秒 之后正常了
By the way, there is a bug, setting card number distance. When the number of started sliding will find spacing or the original settings there came a second after normal

**Comment by lozn00** [comment]
找个问题已经解决了 关于 SDK位置未找到，是我导入的姿势不对,我 好像应该选择指定 项目 ,反正是重启了android studio 然后 选择了指定项目库打开就正常了 非常感谢您的回答
Find a problem has been solved on the SDK location was not found, I imported the posture is not right, I should probably choose to specify project, anyway, is to restart the Android studio and then select the specified project library open normal thank your answer

**Comment by lozn00** [comment]
抱歉 描述可能太清楚详细, 然后翻译过来可能更加不太理解了，语句都写错了,我重新说一遍啦, 就是设置卡片与卡片之间的距离参数 ,我设置为很大了,会发生 布局不足够显示,经过微调已经解决,还有卡片阴影显示效果由底部改成顶部 也弄好了,我本人比较基础不够好,弄了半天才弄好让您见笑了,但是我发现确实有一个bug,就是卡片距离 已经设置很大的了，第一次滑动完毕后会发生距离不对的情况 也就是您所设置的默认距离,之后滑动翻页都是很正常了。

**Comment by lozn00** [comment]
Wrong settings have been sorry description may very well detailed, then translation might come more not quite understand, statement is wrong, I to say again, is to set up the cards and card between the distance parameters I set for large, will happen layout is not enough to show, after fine-tuning has been resolved, as well as the card shadow display from the bottom to top, somehow, I basis of comparison is not good enough, get a half day to complete make you laugh, but I found that does have a bug, is the cards distance great, the first sliding finished after range is you set the default distance, and then slide page is very normal.
