### ISSUE TITLE
Conflict with onClick event from view inside card content

### ISSUE THREAD

**Issue by juanpabloprado** [wenchaojiang/AndroidSwipeableCardStack#56]
The view inside card content somehow consumes the touch event, and the cadStack doesn't listen to the drag gestures, is there a workaround or something we can do, so views inside the card content respond to onClick and drag gestures from CardStack also gets triggered.
I have a video of the undesired behavior below:
https://www.youtube.com/watch?v=jOyM0T69KCA

**Comment by wenchaojiang** [comment]
This is not library specific issue, it is general question of how do you
handle the events. Google it
http://stackoverflow.com/questions/6374592/passing-touch-events-to-the-parent-view
