### ISSUE TITLE
The reason why doesn't it work under API 19?

### ISSUE THREAD

**Issue by rajyvan** [wenchaojiang/AndroidSwipeableCardStack#6]
What are the reasons why doesn't it work under API 19 ? 
Thx!

**Comment by wenchaojiang** [comment]
Hi, 
Some LayoutParams are copied with utility functions, which is not available on 19 or below.

cheers
wenchao

**Comment by wenchaojiang** [comment]
Now it is compatible with level 14

**Comment by rajyvan** [comment]
Big thanks !
