### ISSUE TITLE
How do you change the size of the card

### ISSUE THREAD

**Issue by liveaffiliates** [wenchaojiang/AndroidSwipeableCardStack#65]
I tried to change the size of the card because it is too big for the phone. 

I tried changing the model card xml and I tried changing the xml for the card stack 

but it makes no difference the cards are always the same size. In the stack animation file it has match parent. Is that where the card is getting the default sizing from.

Thanks

**Comment by einverne** [comment]
I have not found any solutions to resize the card, but I found a way to let card become small that you can set the padding to the CardStack like this. This makes the cards a little bit small then the demo.

```
<com.wenchao.cardstack.CardStack
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipChildren="false"
    android:clipToPadding="false"
    android:paddingTop="60dp"
    android:paddingBottom="60dp"
    android:paddingLeft="60dp"
    android:paddingRight="60dp"
    app:stackMargin="20" />
```

**Comment by wenchaojiang** [comment]
Just change cards stack container size
