### ISSUE TITLE
Undo functionality?

### ISSUE THREAD

**Issue by romshiri** [wenchaojiang/AndroidSwipeableCardStack#69]
Hi,

Can you put me in the right direction to implement Undo functionality?
I mean, return an old card to the stack with animation.

Thanks.

**Comment by wenchaojiang** [comment]
Not necessarily the best way.
1. have to provide animators for reversing animation effects.
2. allow data store to temporarily hold deleted items.
3. when undo is triggered, put the data back and trigger reverse animation.

This is quite abstract answer, but good luck with it.

**Comment by wenchaojiang** [comment]
It is now implemented in the new version
https://github.com/wenchaojiang/AndroidSwipeableCardStack/pull/72

**Comment by romshiri** [comment]
Thanks!
