### ISSUE TITLE
Conflict Touch event in CardView 

### ISSUE THREAD

**Issue by CongBaDo** [wenchaojiang/AndroidSwipeableCardStack#7]
I have s ScrollView in CardView, How to touch to move the card. It is conflicted touch event between ScrollView and Cardview

**Comment by wenchaojiang** [comment]
Does your scrollView consume all touch events?
If yes, try to return false in event handlers to bob the event up to CardView

**Comment by bhavikgandhi007** [comment]
I have s ViewPager in CardView, How to touch to move the card. It is conflicted touch event between Viewpager swipe and Cardview swipe left and right
