### ISSUE TITLE
An event to move the cards programmatically

### ISSUE THREAD

**Issue by kaabus** [wenchaojiang/AndroidSwipeableCardStack#70]
Hi, I would like to suggest an event that we can call, and the cards move, say fro eg .I have a button.setOnClickListener, i call this method inside it and the cards swipe.

**Comment by wenchaojiang** [comment]
There is one , called "discard"

**Comment by kaabus** [comment]
Does it left swipe or right swipe ?

**Comment by wenchaojiang** [comment]
the method signature is
void discarded(int mIndex, int direction);

you can set the direction.
