### ISSUE TITLE
Cannot remove padding

### ISSUE THREAD

**Issue by sujan219** [wenchaojiang/AndroidSwipeableCardStack#87]
There is always some padding in the card stack. I want the top card to fill up whole space, I want it to have match_parent as width and height. But I cannot do so, there is always some margin for the top card. Is there any way I can remove this?

**Comment by pesonsita** [comment]
@sujan219, you also have a padding/margin right/end for the top card?

**Comment by sujan219** [comment]
I used negative margins to fix it.

**Comment by OpeyemiSanusi** [comment]
I'm looking okl
